name: dsw53518
description: A new Flutter project.
publish_to: "none"
version: 0.0.1+1
environment:
  sdk: ^3.1.1

dependencies:
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  path: ^1.9.0
  provider: ^6.0.0
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1
  very_good_analysis: ^6.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
